name: Push schema files to gh-pages branch
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}
jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push to gh-pages branch
        env: 
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git_commit_id=$(git rev-parse --short HEAD)
          cd schemas
          echo "schemas.mirrorz.org" > CNAME
          touch .nojekyll
          git init
          git branch -M gh-pages
          git config user.name "Mirrorz Bot"
          git config user.email "bot@mirrorz.org"
          git remote add origin https://token:${ACCESS_TOKEN}@github.com/mirrorz-org/mirrorz-schema.git
          git add .
          git commit -m "Update static files for ${git_commit_id}"
          git push -u origin gh-pages -f

